### ISSUE TITLE
ms_simplify() leading to issues

### ISSUE THREAD

**Issue by MikeJohnPage** [humaniverse/geographr#10]
Running `rmapshaper::ms_simplify()` casues rows to be dropped. This behaviour was unexpected. Look at the below example that returns dataframes of different lengths (note the call to `ms_simplify` is commented out in the second code block):

<img width="886" alt="Screenshot 2021-07-01 at 15 05 46" src="https://user-images.githubusercontent.com/38110953/124129289-f02a4000-da7d-11eb-84a7-2bb11cbd32c3.png">

We need to backtrack through all the R scripts in `/data-raw` and check that rows are not being dropped.

**Comment by VictoriaLatham** [comment]
@MikeJohnPage  I also noticed this issue on the recent boundary file I added and so commented out that part of the code - really not sure why it made ~10 observations be dropped.
